# Dimension Reduction {#sec-reduce-dim}

```{r}
#| label: setup
#| include: false

knitr::opts_chunk$set(
  echo    = FALSE, 
  error   = FALSE, 
  message = FALSE, 
  warning = FALSE
)
```

```{r}
#| label: CRAN-libraries

library(assertthat)
library(beans)
# library(dslabs)
# library(GGally)
# library(ggimg)
# library(HistData)
library(here)
library(ISLR)
# library(keras)
library(knitr)
# library(latex2exp)
# library(OECD)
# library(patchwork)
# library(plotly)
library(regclass)
# library(rgl)
# library(R.utils)
# library(reticulate)
# library(scatterplot3d)
# library(tensorflow)
library(tidyverse)
# library(tinytex)
# library(UsingR)
```

```{r}
#| label: local-source

# source(here("code", "galton_ht_data.R"))
# source(here("code", "mnist_file_mgmt.R"))
# source(here("code", "oecd_bli.R"))
# source(here("code", "pgram_grid.R"))
# source(here("code", "z_score.R"))
```

```{r}
#| label: data-sets

# run only once
run_code <- FALSE
if (run_code) {
  # 1. Dry beans
  install.packages("beans")
  library(beans)
  data(beans)
  ?beans  # Documentation
  
  # 2. Wine quality
  # Option A: From regclass package
  install.packages("regclass")
  library(regclass)
  data(WINE)
  
  # Option B: Direct download from UCI
  wine_url <- "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
  wine <- read.csv(wine_url, sep=";")
  
  # 3. USArrests (already in R)
  data(USArrests)
  
  # 4. NCI60 (optional advanced example)
  install.packages("ISLR")
  library(ISLR)
  data(NCI60)
}
```

