project:
  type: book
  output-dir: _book

book:
  title: "EDA for Machine Learning"
  author: "Tony Thrall"
  date: last-modified
  date-format: HH:mm ddd D-MMM-YYYY
  chapters:
    - index.qmd
    - preface.qmd
    - part: basics.qmd
      chapters: 
        - eda.qmd
        - conditioning.qmd
        - em-algorithm.qmd
        - clustering.qmd
        - simulation.qmd
        - study-design.qmd
    - part: linear-systems.qmd 
      chapters:
        - linear-algebra.qmd
        - dimension-reduction.qmd
    - part: text.qmd
      chapters:
        - text-analysis.qmd
        - dirichlet-dstn.qmd
        - latent-dirichlet-alloc.qmd
    - part: time-series.qmd
      chapters:
        - ts-intro.qmd
        - ts-forecast.qmd
        - ts-fourier.qmd
    - part: graph-theory.qmd
      chapters:
        - graph-intro.qmd
        - large-graphs.qmd
    - summary.qmd
    - references.qmd

bibliography: eda4ml.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: source

