---
title: "part2-review-2025-12-06-1630"
format: html
---

What follows are Tony's review comments on Part 2 of the book, currently consisting of the following two chapters:

  - `la-intro.qmd`: "Linear Regression"
  - `reduce-dim.qmd`: "Dimension Reduction"
    - "PCA: Principal Component Analysis"
    - "LDA: Linear Discriminant Analysis"
    - "Appendix A: Matrix Decomposition and PCA"

## Multiple Related Goals

This part of the book attempts to balance the following goals (listed from highest to lowest priority):

  1. Equip students to apply and extend the data analysis methods shown.
  1. Demonstrate data analysis methods based on linear algebra.
  1. Refresh student knowledge of linear algebra essential to data analysis.
  1. Demonstrate the application of linear algebra to data analysis.
  1. Engage student interest via data analysis case studies.
  
## Major Concepts

  1. Least-squares linear regression _projects_ the target variable onto feature space.
  1. Two complementary perspectives: observations (data rows) and features (data columns).
  1. Problem: to understand and model data, we must simplify the data.
  1. In Part 2, the simplification is to form a relatively small number of linear combinations of features.
  1. In linear regression and linear classification, the number of such linear combinations matches the column-dimension of the target (response/labeling) variable.
  1. In the absence of labels, PCA provides a systematic way to choose the number and composition of such linear combinations.
  1. PCA is a prime example of an _unsupervised_ method.
  
## Related Concepts (not currently mentioned or emphasized)

  1. Linear methods can take us far
    a. Example: logistic regression is the application of linear methods to transformed data.
    a. Example: Project to non-linear manifolds by forming polynomial combinations of features and then applying linear methods (cite ISLR2).
  1. Even so, when one must go farther consider non-linear methods (t-SNE).
  
## Re-organize chapters

### Proposed Split:

  - split `reduce-dim.qmd` into two chapters on: 
    (1) "PCA: Principal Component Analysis"; and 
    (2) "LDA: Linear Discriminant Analysis".
  - move the material on "SVD: Singular Value Decomposition" from a `reduce-dim.qmd` appendix to a book appendix.

### Where to put broad themes?

  1. "How is Linear Algebra relevant to EDA/ML?"
  1. "Dimension Reduction"

Options:
  - Part 2 narrative
  - Roadmap preface to PCA and LDA chapters

I'm not keen on the first option because it breaks the pattern established in Part 1.

## Next steps

  1. Assume a split into three chapters: 
    a. Linear Regression
    a. PCA
    a. LDA
  1. Develop slide-decks, one at a time, for each chapter to drive chapter revision.

Question: file-names for revised chapters?

  1. `lin-reg.qmd`
  1. `pca.qmd`
  1. `lin-discr.qmd`

Note that latent Dirichlet allocation `latent-dirichlet-alloc.qmd` is a rival claimant for the LDA acronym.

